{% set name = "FenicsXConcrete" %}
{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=true) %}
{% set version = pyproject.get('project').get('version') %}
# For setting the version, set the desired value in pyproject.toml
# This should also work for pre-releases like 0.0.1a1
# Next, create/draft a new release with a tag equal to version (prefixed with v)
# and choose the correct branch as target.
# Example: version = "0.0.5a1" in pyproject.toml
# tag --> v0.0.5a1
# See https://peps.python.org/pep-0440/#version-scheme

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BAMresearch/FenicsXConcrete/archive/refs/tags/v{{ version }}.tar.gz

build:
  skip: True  # [win or osx]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - fenics-dolfinx
    - pint
    - python-gmsh
    - jsonschema
    - scipy    

about:
  home: https://github.com/BAMresearch/FenicsXConcrete
  license: MIT
  license_family: MIT
  summary: Computation for concrete structures using FEniCSX
